airflow:
  extraVolumes:
    - name: dags-volume
      hostPath:
        path: "/Users/francisjoseph/Desktop/Projects/airflow/dags"
        type: Directory
  extraVolumeMounts:
    - name: dags-volume
      mountPath: /opt/airflow/dags
      readOnly: true
