apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /Users/francisjoseph/Desktop/Projects/airflow/dags # Replace with the actual path on the Kubernetes node

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
